### ISSUE TITLE
UI Functionality

### ISSUE THREAD

**Issue by williamjsmith15** [williamjsmith15/OmniFlow#15]
# Epic Title

Feature: UI Functionality

## Epic Description

This Feature will... 
Sort out the UI for added functionality so that the User can access more of OpenMC's functionality and have a better overall experience.

## List of Tasks (Complete in order)

1. [x] [Task 1: Save previous settings for new load of extension](https://github.com/williamjsmith15/OmniFlow/issues/16)
2. [ ] [Task 2: Allow choice of boundaries, their locations and type](https://github.com/williamjsmith15/OmniFlow/issues/17)
3. [ ] [Task 3: Material handling, choose from presets](https://github.com/williamjsmith15/OmniFlow/issues/18)
4. [ ] [Task 4: Source Location Indicator](https://github.com/williamjsmith15/OmniFlow/issues/33)
5. [x] [Task 4: Plasma Source](https://github.com/williamjsmith15/OmniFlow/issues/34)

**Comment by williamjsmith15** [comment]
? Save and load presets (so can have different simulation settings files that can be working on at the same time)

**Comment by williamjsmith15** [comment]
Also potential issue with the rotation of the up-axis and point source location - ie fixed it for the ring source case but not for the point source case?
