### ISSUE TITLE
Docker Compose System

### ISSUE THREAD

**Issue by williamjsmith15** [williamjsmith15/OmniFlow#20]
# Epic Title

Feature: Docker Compose System

## Epic Description

This Feature will... allow for more portability of the system as a whole as only docker and omni will need to be downloaded and the docker containers will handle all the running of workflows etc

## List of Tasks (Complete in order)

Pre Task [Task 0: Get System Working in Windows](https://github.com/williamjsmith15/OmniFlow/issues/38)

1. [ ] [Task 1: Workflow Docker Env](https://github.com/williamjsmith15/OmniFlow/issues/22)
2. [ ] [Task 2: Workflows in Containers](https://github.com/williamjsmith15/OmniFlow/issues/22)
3. [ ] [Task 3: Connecting Omni to Containers](https://github.com/williamjsmith15/OmniFlow/issues/23)
4. [ ] [Task 4: Docker compose system](https://github.com/williamjsmith15/OmniFlow/issues/13)
