### ISSUE TITLE
Windows System 

### ISSUE THREAD

**Issue by williamjsmith15** [williamjsmith15/OmniFlow#29]
# Epic Title

Feature: Windows System

## Epic Description

This Feature will... get the omniflow system up and running on windows

## List of Tasks (Complete in order)

1. [ ] [Task 1: Manual Workflows Windows](https://github.com/williamjsmith15/OmniFlow/issues/30)
2. [ ] [Task 2: OpenMC Ext Windows](https://github.com/williamjsmith15/OmniFlow/issues/31)
3. [ ] [Task 3: Windows Fresh Install](https://github.com/williamjsmith15/OmniFlow/issues/32)
