### ISSUE TITLE
Asset Conversion

### ISSUE THREAD

**Issue by williamjsmith15** [williamjsmith15/OmniFlow#4]
# Epic Title

Feature: Asset Conversion

## Epic Description

This Feature will take USD from Omni, convert it to a suitable format for use with DAGMC and then pass it into the rest of the existing workflow.

## List of Tasks (Complete in order)

1. [x] [Task 1: Test Converter](https://github.com/williamjsmith15/OmniFlow/issues/5)
2. [x] [Task 2: Integrate into Manual Workflow](https://github.com/williamjsmith15/OmniFlow/issues/6)
3. [x] [Task 3: Integrate into OmniUI Workflows](https://github.com/williamjsmith15/OmniFlow/issues/7)
4. [x] [Task 4: MDL Passing](https://github.com/williamjsmith15/OmniFlow/issues/8)
5. [x] [Task 5: Converter Mesh Orientation and Location Fix](https://github.com/williamjsmith15/OmniFlow/issues/9)
6. [x] [Task 6: Asset Converter Rotation Issue](https://github.com/williamjsmith15/OmniFlow/issues/14)
